#!/bin/bash

basedir=$(dirname $0)

source ./$basedir/validate_report

echo "Running trivy-gitlab container scan on $1"

go run ./cmd/trivy-gitlab container \
    --target $1 \
    --artifact-dir=$PWD

reports=("trivy-container-scanning-report.json" "trivy-dependency-scanning-report.json")

validate_reports "${reports[@]}"
