#!/bin/bash

basedir=$(dirname $0)

source ./$basedir/validate_report

go run ./cmd/trivy-gitlab container $1 \
    --template-path=$PWD/templates/report/container-scanning.tpl \
    --report-path=$PWD \
    --debug

validate_report trivy-container-scanning-report.json
# validate_report trivy-dependency-scanning-report.json
