#!/bin/bash

basedir=$(dirname $0)

source ./$basedir/validate_report

go run ./cmd/trivy-gitlab dependency $1 \
    --template-path=$PWD/templates/report/dependency-scanning.tpl \
    --report-path=$PWD \
    --debug

validate_report trivy-dependency-scanning-report.json
