#!/bin/bash

basedir=$(dirname $0)

source ./$basedir/validate_report

go run ./cmd/trivy-gitlab secret $1 \
    --template-path=$PWD/templates/report/secret-detection.tpl \
    --report-path=$PWD \
    --debug

validate_report trivy-secret-detection-report.json
