project_name: trivy-gtilab
before:
    hooks:
        - go mod tidy
builds:
    - main: cmd/trivy-gitlab/main.go
      binary: trivy-gitlab
      ldflags:
          - -s -w
          - "-extldflags '-static'"
          - -X main.version={{.Version}}
      goos:
          - darwin
          - linux
          - freebsd
          - windows
      goarch:
          - amd64
          - '386'
          - arm
          - arm64
          - s390x
          - ppc64le
      goarm:
          - '7'

      ignore:
          - goos: darwin
            goarch: '386'
          - goos: freebsd
            goarch: arm
          - goos: freebsd
            goarch: arm64
          - goos: windows
            goarch: '386'
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: s390x
          - goos: windows
            goarch: ppc64le

archives:
    - format: tar.gz
      name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
      files:
          - README.md
          - LICENSE
          - plugin.yaml
          - templates
      format_overrides:
          - goos: windows
            format: zip
