name: 'trivy-gitlab'
repository: github.com/afdesk/trivy-gitlab
version: '0.0.1'
usage: ...
description: |-
    ...
platforms:
    - uri: http://271f-176-67-55-113.ngrok-free.app/trivy-gitlab.tar.gz
      bin: ./trivy-gitlab
