name: 'trivy-gitlab'
repository: github.com/afdesk/trivy-gitlab
version: '0.0.1'
usage: ...
description: |-
    ...
platforms:
    - uri: http://d8e0-64-225-69-54.ngrok-free.app/trivy-gitlab.tar.gz
      bin: ./trivy-gitlab
