name: 'trivy-gitlab'
repository: github.com/afdesk/trivy-gitlab
version: '0.0.1'
usage: ...
description: |-
    ...
platforms:
    - uri: https://github.com/afdesk/trivy-gitlab/releases/latest/download/trivy-gitlab.tar.gz
      bin: ./trivy-gitlab
