#!/bin/bash

function usage() {
  cat <<EOS >&2
Usage: trivy trivy-gitlab [-h,--help]
    TODO...

Options:
    -h, --help         Show usage.

Examples:
    trivy trivy-gitlab TODO...
EOS
  exit
}

args=()

for arg; do
  case "$arg" in
  --help)
    args+=(-h)
    ;;
  *)
    args+=("$arg")
    ;;
  esac
done

set -- "${args[@]}"

while getopts "ah" opt; do
  case ${opt} in
  h)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
  esac
done

shift "$((OPTIND - 1))"

tmp_json_file="scan-result.json"

function entrypoint() {
  TEMP_DIR=$(mktemp -d)
  args=("${@:2:$#-2}")
  last_arg="${!#}"
  set -- "$1" "${args[@]}" "$last_arg"

  trivy "$1" --format json -o "$TEMP_DIR"/$tmp_json_file "${args[@]}"

#  trivy_version=$(trivy -v | grep Version | awk 'FNR == 1 {print $2}')
#  cat "$TEMP_DIR"/$tmp_json_file
  trap 'rm -rf -- "$TEMP_DIR"' EXIT
}

entrypoint "$@"