include:
    - template: Secutiry/Container-Scanning.gitlab-ci.yml

stages:
    - build
    - test

variables:
    SOURCE_IMAGE: python
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build_img:
    stage: build
    script:
        - docker pull $SOURCE_IMAGE
        - docker tag $SOURCE_IMAGE $CONTAINER_TEST_IMAGE
        - docker login -u “$CI_REGISTRY_USER” -p “$CI_REGISTRY_PASSWORD” $CI_REGISTRY
        - docker push $CONTAINER_TEST_IMAGE
        - docker logout

container_scanning:
    stage: test
    variables:
        CS_IMAGE: $CONTAINER_TEST_IMAGE
