variables:
    TRIVY_TAG: '0.39.1'
    TRIVY_IMAGE: 'aquasec/trivy:$TRIVY_TAG'

.trivy-container_scanning:
    stage: test
    variables:
        GIT_STRATEGY: none
    allow_failure: true
    artifacts:
        reports:
            container_scanning: trivy-container-scanning-report.json
            dependency_scanning: trivy-dependency-scanning-report.json
        paths:
            - trivy-container-scanning-report.json
            - trivy-dependency-scanning-report.json
    rules:
        - if: $CI_COMMIT_BRANCH

trivy-container_scanning:
    extends:
        - .trivy-container_scanning
    script:
        - >
            docker pull $TRIVY_IMAGE

            export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")

            if [ -z "$CONTAINER_ID" ]; then
                docker run --rm \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -v ${CI_PROJECT_DIR}:/glproject \
                    --env-file <(env | grep 'CI\|TS') \
                    -e DOCKER_IMAGE \
                    -e CONTAINER_SCANNING_DISABLED \
                    $TRIVY_IMAGE plugin run github.com/afdesk/trivy-gitlab \
                    container -- --target=$TS_IMAGE --artifact-dir="/glproject"
            else
                docker run --rm \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    --volumes-from ${CONTAINER_ID} \
                    --env-file <(env | grep 'CI\|TS') \
                    -e DOCKER_IMAGE \
                    -e CONTAINER_SCANNING_DISABLED \
                    $TRIVY_IMAGE plugin run github.com/afdesk/trivy-gitlab \
                    container -- --target=$TS_IMAGE --artifact-dir="${CI_PROJECT_DIR}"
            fi
